import { useMemo, useState } from 'react';
import { useStore } from '../store/useStore';
import type { EREntity, ERField } from '../api/client';

type OutputType = 'object' | 'dataAccess';

function csType(field: ERField) {
  const t=(field.dataType||'').toLowerCase();
  let r:string;
  switch(t){case'bigint':r='Int64';break;case'smallint':r='Int16';break;case'tinyint':r='Byte';break;case'int':r='Int32';break;case'bit':case'boolean':r='Boolean';break;case'decimal':case'numeric':case'money':case'smallmoney':r='Decimal';break;case'float':r='Double';break;case'real':r='Single';break;case'date':case'datetime':case'datetime2':case'smalldatetime':r='DateTime';break;case'time':r='TimeSpan';break;case'uniqueidentifier':case'uuid':r='Guid';break;case'binary':case'varbinary':case'image':case'timestamp':r='Byte[]';break;default:r='String';}
  return field.isNullable && r!=='String' && r!=='Byte[]' ? r+'?' : r;
}
function csDefault(field: ERField){if(field.isNullable)return'null';switch(csType(field).replace('?','')){case'Int64':return'Int64.MinValue';case'Int32':return'Int32.MinValue';case'Int16':return'Int16.MinValue';case'Byte':return'Byte.MinValue';case'Boolean':return'false';case'Decimal':return'Decimal.MinValue';case'Double':return'Double.MinValue';case'Single':return'Single.MinValue';case'DateTime':return'DateTime.MinValue';case'TimeSpan':return'TimeSpan.Zero';case'Guid':return'Guid.Empty';default:return'null';}}
function objectCode(e:EREntity,ns:string){const props=e.fields.map(f=>`        /// <summary>\n        /// ${f.notes||''}\n        /// </summary>\n        public ${csType(f)} ${f.name} { get; set; } = ${csDefault(f)};`).join('\n\n');const ip=e.fields.map(f=>`        ${csType(f)} ${f.name} { get; set; }`).join('\n');return `using System;\nusing System.Collections;\n\nnamespace ${ns}.ObjectLayer.Schema\n{\n    /// <summary>\n    /// T${e.name} 的摘要描述\n    /// ${e.notes||''}\n    /// </summary>\n    public partial class T${e.name} : I${e.name}\n    {\n${props}\n    }\n\n    public interface I${e.name}\n    {\n${ip}\n    }\n}\n`;}
function dataCode(e:EREntity,ns:string){const ef=e.fields.map((f,i)=>`        ${f.columnName||f.name} = ${2**Math.min(i,30)}`).join(',\n');const cond=e.fields.map(f=>`            if ((stint.Field & ${e.name}Field.${f.columnName||f.name}) == ${e.name}Field.${f.columnName||f.name})\n                SqlBuilder.AddCond("${f.columnName||f.name}", stint[${e.name}Field.${f.columnName||f.name}]);`).join('\n');const df=e.fields.filter(f=>(f as any).isIdentity!==true).map(f=>`            SqlBuilder.AddField("${f.columnName||f.name}");`).join('\n');const keys=e.fields.filter(f=>f.isPrimaryKey).map(f=>`            SqlBuilder.AddKeyField("${f.columnName||f.name}");`).join('\n');return `using System;\nusing System.Data;\nusing System.Collections.ObjectModel;\nusing PioLibraryCore;\nusing PioLibraryCore.DataAccessLayer;\nusing PioLibraryCore.DataAccessLayer.Schema;\nusing ${ns}.ObjectLayer.Schema;\n\nnamespace ${ns}.DataAccessLayer.Schema\n{\n    [Flags]\n    public enum ${e.name}Field\n    {\n${ef}\n    }\n\n    public partial class ${e.name}DataAccess<${e.name}> : DataAccess<TStint<${e.name}Field>, ${e.name}Field, ${e.name}> where ${e.name} : I${e.name}, new()\n    {\n        public ${e.name}DataAccess() { this.TableName = "${e.tableName||e.name}"; }\n\n        protected override void AddConds(BaseSqlBuilder SqlBuilder, TStint<${e.name}Field> stint)\n        {\n${cond}\n        }\n\n        protected override void SetParameter(IDataBase DBBase, TStint<${e.name}Field> stint) { }\n        protected override void SetParameter(IDataBase DBBase, ${e.name} obj) { }\n        protected override void AddDataField(UpdateSqlBuilder SqlBuilder)\n        {\n${df}\n        }\n        protected override void AddUpdateKeyField(UpdateSqlBuilder SqlBuilder)\n        {\n${keys}\n        }\n        protected override void SetUpdateKeyParameter(IDataBase DBBase, ${e.name} obj) { }\n    }\n}\n`;}

export default function CodeGenerator(){
 const entities=useStore(s=>s.erEntities); const [selected,setSelected]=useState<string>(''); const [ns,setNs]=useState('DemoProject'); const [type,setType]=useState<OutputType>('object');
 const sorted=useMemo(()=>entities.slice().sort((a,b)=>a.name.localeCompare(b.name)),[entities]); const entity=entities.find(e=>e.id===(selected||sorted[0]?.id)); const code=entity?(type==='object'?objectCode(entity,ns.trim()||'DemoProject'):dataCode(entity,ns.trim()||'DemoProject')):'';
 const download=()=>{if(!entity)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([code],{type:'text/plain;charset=utf-8'}));a.download=type==='object'?`T${entity.name}.cs`:`${entity.name}DataAccess.cs`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="codegen-page"><div className="codegen-toolbar"><strong>C# Code Generator</strong><label>Namespace <input value={ns} onChange={e=>setNs(e.target.value)}/></label><select value={type} onChange={e=>setType(e.target.value as OutputType)}><option value="object">ObjectLayer</option><option value="dataAccess">DataAccessLayer</option></select><button className="btn btn-sm" onClick={()=>navigator.clipboard.writeText(code)}>📋 複製</button><button className="btn btn-primary btn-sm" onClick={download}>⬇️ 下載 .cs</button></div><div className="codegen-workspace"><aside><div className="codegen-title">Entity ({sorted.length})</div>{sorted.map(e=><button key={e.id} className={entity?.id===e.id?'active':''} onClick={()=>setSelected(e.id)}><strong>{e.name}</strong><small>{e.tableName||e.name} · {e.fields.length} fields</small></button>)}</aside><pre className="codegen-preview">{code||'// CASE Studio 目前沒有 Entity'}</pre></div></div>;
}