// Frontend DDL Generator - generates SQL from ER entities
import type { EREntity, ERField } from '../api/client';

export type DDLTarget = 'mysql' | 'postgresql' | 'sqlserver';

interface DDLResult {
  target: string;
  ddl: string;
  warnings: string[];
}

function quote(name: string, target: DDLTarget): string {
  switch (target) {
    case 'mysql': return `\`${name}\``;
    case 'postgresql': return `"${name}"`;
    case 'sqlserver': return `[${name}]`;
  }
}

function mapType(field: ERField, target: DDLTarget): string {
  let t = field.dataType.toUpperCase();

  // Type mappings per target
  if (target === 'mysql') {
    if (t === 'NVARCHAR') t = 'VARCHAR';
    if (t === 'NCHAR') t = 'CHAR';
    if (t === 'NTEXT') t = 'TEXT';
    if (t === 'DATETIME2') t = 'DATETIME';
    if (t === 'BIT') t = 'TINYINT(1)';
    if (t === 'UNIQUEIDENTIFIER') t = 'CHAR(36)';
  } else if (target === 'postgresql') {
    if (t === 'NVARCHAR') t = 'VARCHAR';
    if (t === 'NCHAR') t = 'CHAR';
    if (t === 'NTEXT') t = 'TEXT';
    if (t === 'DATETIME2') t = 'TIMESTAMP';
    if (t === 'DATETIME') t = 'TIMESTAMP';
    if (t === 'BIT') t = 'BOOLEAN';
    if (t === 'INT') t = 'INTEGER';
    if (t === 'TINYINT') t = 'SMALLINT';
    if (t === 'UNIQUEIDENTIFIER') t = 'UUID';
    if (t === 'IMAGE') t = 'BYTEA';
    if (t === 'MONEY') t = 'NUMERIC(19,4)';
  } else if (target === 'sqlserver') {
    if (t === 'BOOLEAN') t = 'BIT';
    if (t === 'TIMESTAMP') t = 'DATETIME2';
    if (t === 'UUID') t = 'UNIQUEIDENTIFIER';
    if (t === 'BYTEA') t = 'VARBINARY(MAX)';
    if (t === 'TEXT') t = 'NVARCHAR(MAX)';
  }

  // Add length/precision
  if (['VARCHAR', 'NVARCHAR', 'CHAR', 'NCHAR', 'VARBINARY'].includes(t)) {
    const len = field.length ?? 255;
    return `${t}(${len})`;
  }
  if (['DECIMAL', 'NUMERIC'].includes(t)) {
    const p = field.precision ?? 18;
    const s = field.scale ?? 0;
    return `${t}(${p},${s})`;
  }

  return t;
}

export function generateDDL(entities: EREntity[], target: DDLTarget): DDLResult {
  const lines: string[] = [];
  const warnings: string[] = [];
  const q = (s: string) => quote(s, target);

  lines.push(`-- Generated by CaseTool`);
  lines.push(`-- Target: ${target.toUpperCase()}`);
  lines.push(`-- Date: ${new Date().toISOString()}\n`);

  for (const entity of entities) {
    if (entity.fields.length === 0) {
      warnings.push(`Entity "${entity.name}" has no fields, skipped.`);
      continue;
    }

    lines.push(`CREATE TABLE ${q(entity.name)} (`);
    const fieldDefs: string[] = [];
    const pkFields: string[] = [];

    for (const field of entity.fields) {
      let def = `  ${q(field.name)} ${mapType(field, target)}`;
      if (!field.isNullable) def += ' NOT NULL';
      if (field.isUnique && !field.isPrimaryKey) def += ' UNIQUE';
      if (field.hasDefault && field.defaultValue) {
        def += ` DEFAULT ${field.defaultValue}`;
      }
      if (field.isPrimaryKey) pkFields.push(q(field.name));
      fieldDefs.push(def);
    }

    // Primary key
    if (pkFields.length > 0) {
      fieldDefs.push(`  CONSTRAINT ${q(`PK_${entity.name}`)} PRIMARY KEY (${pkFields.join(', ')})`);
    }

    lines.push(fieldDefs.join(',\n'));
    lines.push(');\n');
  }

  // Foreign keys as ALTER TABLE
  for (const entity of entities) {
    const fkFields = entity.fields.filter(f => f.isForeignKey && f.referencedEntity);
    for (const fk of fkFields) {
      const refEntity = entities.find(e => e.id === fk.referencedEntity);
      const refField = refEntity?.fields.find(f => f.id === fk.referencedField);
      if (refEntity && refField) {
        lines.push(`ALTER TABLE ${q(entity.name)}`);
        lines.push(`  ADD CONSTRAINT ${q(`FK_${entity.name}_${fk.name}`)}`);
        lines.push(`  FOREIGN KEY (${q(fk.name)}) REFERENCES ${q(refEntity.name)}(${q(refField.name)});`);
        lines.push('');
      } else {
        warnings.push(`FK "${fk.name}" in "${entity.name}" has invalid reference.`);
      }
    }
  }

  return {
    target: target.toUpperCase(),
    ddl: lines.join('\n'),
    warnings,
  };
}
