// Frontend DDL Generator - generates SQL from ER entities
import type { EREntity, ERField } from '../api/client';

export type DDLTarget = 'sqlserver' | 'sqlite' | 'mysql' | 'postgresql';

interface DDLResult {
  target: string;
  ddl: string;
  warnings: string[];
}

function quote(name: string, target: DDLTarget): string {
  switch (target) {
    case 'mysql': return `\`${name}\``;
    case 'postgresql': return `"${name}"`;
    case 'sqlite': return `"${name}"`;
    case 'sqlserver': return `[${name}]`;
  }
}

function mapType(field: ERField, target: DDLTarget): string {
  let t = field.dataType.toUpperCase();

  // Type mappings per target
  if (target === 'sqlite') {
    if (['TINYINT','SMALLINT','BIGINT','BIT','BOOLEAN'].includes(t)) t = 'INTEGER';
    if (['NVARCHAR','NCHAR','NTEXT','VARCHAR','CHAR'].includes(t)) t = 'TEXT';
    if (['DATETIME','DATETIME2','SMALLDATETIME','DATE','TIME','TIMESTAMP'].includes(t)) t = 'TEXT';
    if (['DECIMAL','NUMERIC','MONEY','FLOAT','REAL'].includes(t)) t = 'REAL';
    if (['VARBINARY','IMAGE'].includes(t)) t = 'BLOB';
    if (['UUID','UNIQUEIDENTIFIER'].includes(t)) t = 'TEXT';
  } else if (target === 'mysql') {
    if (t === 'NVARCHAR') t = 'VARCHAR';
    if (t === 'NCHAR') t = 'CHAR';
    if (t === 'NTEXT') t = 'TEXT';
    if (t === 'DATETIME2') t = 'DATETIME';
    if (t === 'BIT') t = 'TINYINT(1)';
    if (t === 'UNIQUEIDENTIFIER') t = 'CHAR(36)';
  } else if (target === 'postgresql') {
    if (t === 'NVARCHAR') t = 'VARCHAR';
    if (t === 'NCHAR') t = 'CHAR';
    if (t === 'NTEXT') t = 'TEXT';
    if (t === 'DATETIME2') t = 'TIMESTAMP';
    if (t === 'DATETIME') t = 'TIMESTAMP';
    if (t === 'BIT') t = 'BOOLEAN';
    if (t === 'INT') t = 'INTEGER';
    if (t === 'TINYINT') t = 'SMALLINT';
    if (t === 'UNIQUEIDENTIFIER') t = 'UUID';
    if (t === 'IMAGE') t = 'BYTEA';
    if (t === 'MONEY') t = 'NUMERIC(19,4)';
  } else if (target === 'sqlserver') {
    if (t === 'BOOLEAN') t = 'BIT';
    if (t === 'TIMESTAMP') t = 'DATETIME2';
    if (t === 'UUID') t = 'UNIQUEIDENTIFIER';
    if (t === 'BYTEA') t = 'VARBINARY(MAX)';
    if (t === 'TEXT') t = 'NVARCHAR(MAX)';
  }

  // Add length/precision
  if (['VARCHAR', 'NVARCHAR', 'CHAR', 'NCHAR', 'VARBINARY'].includes(t)) {
    const len = field.length ?? 255;
    return `${t}(${len})`;
  }
  if (['DECIMAL', 'NUMERIC'].includes(t)) {
    const p = field.precision ?? 18;
    const s = field.scale ?? 0;
    return `${t}(${p},${s})`;
  }

  return t;
}

export function generateDDL(entities: EREntity[], target: DDLTarget): DDLResult {
  const lines: string[] = [];
  const warnings: string[] = [];
  const q = (s: string) => quote(s, target);
  const sqlString = (s: string) => `'${s.replace(/'/g, "''")}'`;

  lines.push(`-- Generated by CaseTool`);
  lines.push(`-- Target: ${target.toUpperCase()}`);
  lines.push(`-- Date: ${new Date().toISOString()}\n`);

  for (const entity of entities) {
    if (entity.fields.length === 0) {
      warnings.push(`Entity "${entity.name}" has no fields, skipped.`);
      continue;
    }

    lines.push(`CREATE TABLE ${q(entity.tableName ?? entity.name)} (`);
    const fieldDefs: string[] = [];
    const pkFields: string[] = [];

    for (const field of entity.fields) {
      let def = `  ${q(field.columnName ?? field.name)} ${mapType(field, target)}`;
      if (!field.isNullable) def += ' NOT NULL';
      if (field.isUnique && !field.isPrimaryKey) def += ' UNIQUE';
      if (field.hasDefault && field.defaultValue) {
        def += ` DEFAULT ${field.defaultValue}`;
      }
      if (field.isPrimaryKey) pkFields.push(q(field.columnName ?? field.name));
      fieldDefs.push(def);
    }

    // Check constraints
    for (const ck of entity.checkConstraints ?? []) {
      if (!ck.name.trim() || !ck.expression.trim()) {
        warnings.push(`Check Constraint "${ck.name || '(unnamed)'}" in "${entity.name}" is incomplete.`);
        continue;
      }
      fieldDefs.push(`  CONSTRAINT ${q(ck.name)} CHECK (${ck.expression})`);
    }

    // Primary key
    if (pkFields.length > 0) {
      fieldDefs.push(`  CONSTRAINT ${q(`PK_${entity.name}`)} PRIMARY KEY (${pkFields.join(', ')})`);
    }

    lines.push(fieldDefs.join(',\n'));
    lines.push(');');

    // Export entity / field descriptions using the native mechanism of each database.
    const tableName = entity.tableName ?? entity.name;
    const entityDesc = entity.notes?.trim();
    const describedFields = entity.fields.filter(field => field.notes?.trim());
    if (target === 'sqlserver') {
      if (entityDesc) lines.push(`EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N${sqlString(entityDesc)}, @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N${sqlString(tableName)};`);
      for (const field of describedFields) lines.push(`EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N${sqlString(field.notes!.trim())}, @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N${sqlString(tableName)}, @level2type=N'COLUMN', @level2name=N${sqlString(field.columnName ?? field.name)};`);
    } else if (target === 'mysql') {
      if (entityDesc) lines.push(`ALTER TABLE ${q(tableName)} COMMENT = ${sqlString(entityDesc)};`);
      for (const field of describedFields) warnings.push(`MySQL 欄位 Description："${entity.name}.${field.name}" 需要重述完整欄位型別才能 ALTER COMMENT，目前未自動修改欄位定義。`);
    } else if (target === 'postgresql') {
      if (entityDesc) lines.push(`COMMENT ON TABLE ${q(tableName)} IS ${sqlString(entityDesc)};`);
      for (const field of describedFields) lines.push(`COMMENT ON COLUMN ${q(tableName)}.${q(field.columnName ?? field.name)} IS ${sqlString(field.notes!.trim())};`);
    } else if (target === 'sqlite' && (entityDesc || describedFields.length)) {
      lines.push('-- SQLite 不支援資料庫層級的 table/column description；以下保留為註解。');
      if (entityDesc) lines.push(`-- ${tableName}: ${entityDesc.replace(/\\r?\\n/g, ' ')}`);
      for (const field of describedFields) lines.push(`-- ${tableName}.${field.columnName ?? field.name}: ${field.notes!.trim().replace(/\\r?\\n/g, ' ')}`);
    }

    // Alternate keys are modeled as UNIQUE constraints.
    for (const ak of entity.alternateKeys ?? []) {
      const cols = ak.fieldIds.map(id => entity.fields.find(f => f.id === id)).filter((f): f is ERField => !!f);
      if (cols.length !== ak.fieldIds.length || !cols.length) {
        warnings.push(`Alternate Key "${ak.name}" in "${entity.name}" has invalid/no columns.`);
        continue;
      }
      lines.push(`ALTER TABLE ${q(entity.tableName ?? entity.name)} ADD CONSTRAINT ${q(ak.name)} UNIQUE (${cols.map(f => q(f.columnName ?? f.name)).join(', ')});`);
    }

    // Secondary indexes.
    for (const index of entity.indexes ?? []) {
      const cols = index.fieldIds.map(id => entity.fields.find(f => f.id === id)).filter((f): f is ERField => !!f);
      if (cols.length !== index.fieldIds.length || !cols.length) {
        warnings.push(`Index "${index.name}" in "${entity.name}" has invalid/no columns.`);
        continue;
      }
      lines.push(`CREATE ${index.isUnique ? 'UNIQUE ' : ''}INDEX ${q(index.name)} ON ${q(entity.tableName ?? entity.name)} (${cols.map(f => q(f.columnName ?? f.name)).join(', ')});`);
    }
    lines.push('');
  }

  // Foreign keys as ALTER TABLE
  for (const entity of entities) {
    const fkFields = entity.fields.filter(f => f.isForeignKey && f.referencedEntity);
    for (const fk of fkFields) {
      const refEntity = entities.find(e => e.id === fk.referencedEntity);
      const refField = refEntity?.fields.find(f => f.id === fk.referencedField);
      if (refEntity && refField) {
        lines.push(`ALTER TABLE ${q(entity.tableName ?? entity.name)}`);
        lines.push(`  ADD CONSTRAINT ${q(`FK_${entity.name}_${fk.name}`)}`);
        lines.push(`  FOREIGN KEY (${q(fk.columnName ?? fk.name)}) REFERENCES ${q(refEntity.tableName ?? refEntity.name)}(${q(refField.columnName ?? refField.name)});`);
        lines.push('');
      } else {
        warnings.push(`FK "${fk.name}" in "${entity.name}" has invalid reference.`);
      }
    }
  }

  return {
    target: target.toUpperCase(),
    ddl: lines.join('\n'),
    warnings,
  };
}
